version: '3'
services:
  client:
    build: ./fronend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://server:8080
  server:
    build: ./server
    ports:
      - "8080:8080"
